import type { Mission } from '../engine/types'

export const MISSIONS: Mission[] = [
  {
    id: 'p1-frigo',
    season: 1,
    room: 'kitchen',
    title: 'Le frigo envahi',
    intro: 'Les Lemmings ont ouvert le frigo de Grizzy ! Aide-le à compter les farceurs.',
    competenceId: 'denombre-10',
    sequence: [
      { type: 'count', max: 5, item: 'lemming' },
      { type: 'count', max: 8, item: 'lemming' },
      { type: 'count', max: 10, item: 'lemming' },
      { type: 'build-collection', max: 6, item: 'lemming' },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-pots',
    season: 1,
    room: 'kitchen',
    title: 'Les pots de tartinade',
    intro: 'Grizzy veut sa tartinade. Donne-lui exactement le bon nombre de pots.',
    competenceId: 'construire-10',
    sequence: [
      { type: 'build-collection', max: 4 },
      { type: 'build-collection', max: 7 },
      { type: 'build-collection', max: 10 },
      { type: 'count', max: 9 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-etiquettes',
    season: 1,
    room: 'kitchen',
    title: 'Les étiquettes du frigo',
    intro: 'Les Lemmings ont arraché les étiquettes. Réécris les nombres.',
    competenceId: 'ecrire-lire-10',
    sequence: [
      { type: 'write-digits', min: 0, max: 5 },
      { type: 'write-digits', min: 4, max: 10 },
      { type: 'write-digits', min: 0, max: 10 },
      { type: 'count', max: 7 },
      { type: 'hole-equality', max: 10 },
    ],
  },
  {
    id: 'p1-plus',
    season: 1,
    room: 'living',
    title: 'Qui a le plus de tartinade ?',
    intro: 'Grizzy et les Lemmings se disputent les pots. Qui en a le plus ?',
    competenceId: 'comparer-10',
    sequence: [
      { type: 'compare', max: 6 },
      { type: 'compare', max: 10 },
      { type: 'compare', max: 10 },
      { type: 'count', max: 8 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-suite',
    season: 1,
    room: 'living',
    title: 'La file devant la télé',
    intro: 'Les Lemmings se mettent en file. Compte, et trouve le suivant.',
    competenceId: 'suite-orale',
    sequence: [
      { type: 'number-line', max: 10 },
      { type: 'write-digits', max: 10 },
      { type: 'hole-equality', max: 10 },
      { type: 'ordinal', max: 8 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-doubles',
    season: 1,
    room: 'kitchen',
    title: 'Deux fois trop de Lemmings',
    intro: 'Partout où Grizzy pose un pot, deux Lemmings apparaissent !',
    competenceId: 'doubles-10',
    sequence: [
      { type: 'hole-equality', max: 10 },
      { type: 'hole-equality', max: 10 },
      { type: 'times-as-add', max: 10 },
      { type: 'write-digits', max: 10 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-dix',
    season: 1,
    room: 'attic',
    title: 'La boîte de dix',
    intro: 'Une caisse est pleine seulement avec dix. Complète-la.',
    competenceId: 'decompo-10',
    sequence: [
      { type: 'hole-equality', max: 10 },
      { type: 'hole-equality', max: 10 },
      { type: 'build-collection', max: 10 },
      { type: 'group-ten', max: 14 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-probleme',
    season: 1,
    room: 'living',
    title: 'Le grand bazar du salon',
    intro: 'Comprendre, dessiner, calculer, répondre. Comme à l’école, avec Grizzy.',
    competenceId: 'pb-pt-10',
    sequence: [
      { type: 'problem-4ph', max: 10, bank: 'p1' },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
      { type: 'count', max: 8 },
      { type: 'problem-4ph', max: 10, bank: 'p1' },
    ],
  },
  {
    id: 'p1-chemin',
    season: 1,
    room: 'garden',
    title: 'Le sentier du frigo',
    intro: 'Guide un Lemming : haut, bas, gauche, droite.',
    competenceId: 'spatial-base',
    sequence: [
      { type: 'move-code', max: 10 },
      { type: 'move-code', max: 10 },
      { type: 'ordinal', max: 6 },
      { type: 'shape', max: 10 },
    ],
  },
  {
    id: 'p1-cables',
    season: 1,
    room: 'workshop',
    title: 'Les câbles de la télé',
    intro: 'Les Lemmings ont tiré tous les câbles. Lequel est le plus long ?',
    competenceId: 'longueurs-compare',
    sequence: [
      { type: 'length', max: 10 },
      { type: 'length', max: 10 },
      { type: 'mass', max: 10 },
      { type: 'compare', max: 8 },
    ],
  },
  {
    id: 'p1-tri',
    season: 1,
    room: 'notebook',
    title: 'Le carnet de forestier',
    intro: 'Compte les pots de chaque jour. Grizzy veut son tableau.',
    competenceId: 'tri-critere',
    sequence: [
      { type: 'tally-table', max: 8 },
      { type: 'tally-table', max: 8 },
      { type: 'bar-chart', max: 8 },
      { type: 'count', max: 7 },
    ],
  },

  {
    id: 'p2-vingt',
    season: 2,
    room: 'kitchen',
    title: 'Vingt Lemmings dans le frigo',
    intro: 'Ils sont trop nombreux pour les compter un par un… ou presque.',
    competenceId: 'nombres-20',
    sequence: [
      { type: 'count', max: 12 },
      { type: 'write-digits', min: 11, max: 20 },
      { type: 'number-line', max: 20 },
      { type: 'compare', max: 20 },
      { type: 'problem-4ph', max: 20, bank: 'p2' },
    ],
  },
  {
    id: 'p2-caisses',
    season: 2,
    room: 'attic',
    title: 'Les caisses de dix',
    intro: 'Range les Lemmings : dix par caisse, le reste à côté.',
    competenceId: 'unites-dizaines',
    sequence: [
      { type: 'group-ten', max: 39 },
      { type: 'group-ten', max: 49 },
      { type: 'match-reps', max: 45 },
      { type: 'write-digits', min: 20, max: 50 },
    ],
  },
  {
    id: 'p2-59',
    season: 2,
    room: 'attic',
    title: 'Jusqu’à cinquante-neuf',
    intro: 'Le grenier déborde. Lis, écris, compare.',
    competenceId: 'nombres-59',
    sequence: [
      { type: 'write-digits', min: 30, max: 59 },
      { type: 'compare', max: 59 },
      { type: 'match-reps', max: 59 },
      { type: 'number-line', max: 20 },
    ],
  },
  {
    id: 'p2-masques',
    season: 2,
    room: 'living',
    title: 'Le même nombre, quatre costumes',
    intro: 'Cubes, chiffres, trente plus quatre, « trente-quatre ». C’est le même !',
    competenceId: 'reps-multiples',
    sequence: [
      { type: 'match-reps', max: 48 },
      { type: 'match-reps', max: 55 },
      { type: 'group-ten', max: 46 },
      { type: 'write-digits', min: 21, max: 55 },
    ],
  },
  {
    id: 'p2-mental',
    season: 2,
    room: 'living',
    title: 'Réveil du canapé',
    intro: 'Grizzy calcule sans se lever. À toi les additions.',
    competenceId: 'add-mentale',
    sequence: [
      { type: 'hole-equality', max: 20 },
      { type: 'hole-equality', max: 20 },
      { type: 'procedure-slate', max: 40 },
      { type: 'problem-4ph', max: 20, bank: 'p2' },
    ],
  },
  {
    id: 'p2-comp10',
    season: 2,
    room: 'attic',
    title: 'Il en manque pour dix',
    intro: 'Complète la caisse : combien pour faire dix ?',
    competenceId: 'complements-10',
    sequence: [
      { type: 'hole-equality', max: 10 },
      { type: 'hole-equality', max: 10 },
      { type: 'build-collection', max: 10 },
      { type: 'fluency', max: 10 },
    ],
  },
  {
    id: 'p2-euros',
    season: 2,
    room: 'chest',
    title: 'Le coffre du forestier',
    intro: 'Pièces de 1 et 2 euros, billets de 5 et 10. Compose la somme.',
    competenceId: 'monnaie-intro',
    sequence: [
      { type: 'money', max: 10 },
      { type: 'money', max: 15 },
      { type: 'money', max: 12 },
      { type: 'write-digits', max: 20 },
    ],
  },
  {
    id: 'p2-formes',
    season: 2,
    room: 'garden',
    title: 'Les formes cassées',
    intro: 'Les Lemmings ont cassé les cadres. Retrouve carré, rectangle, triangle, cercle.',
    competenceId: 'formes-lignes',
    sequence: [
      { type: 'shape', max: 10 },
      { type: 'shape', max: 10 },
      { type: 'grid-draw', max: 10 },
      { type: 'move-code', max: 10 },
    ],
  },
  {
    id: 'p2-tableau',
    season: 2,
    room: 'notebook',
    title: 'Pots de la semaine',
    intro: 'Lis le tableau : combien de pots chaque jour ?',
    competenceId: 'tableau-1',
    sequence: [
      { type: 'tally-table', max: 10 },
      { type: 'tally-table', max: 10 },
      { type: 'bar-chart', max: 10 },
      { type: 'compare', max: 12 },
    ],
  },

  {
    id: 'p3-cent',
    season: 3,
    room: 'attic',
    title: 'Jusqu’à cent',
    intro: 'Le grenier est plein jusqu’en haut. Nombres jusqu’à 100.',
    competenceId: 'nombres-100',
    sequence: [
      { type: 'write-digits', min: 60, max: 100 },
      { type: 'compare', max: 100 },
      { type: 'match-reps', max: 99 },
      { type: 'number-line', max: 20 },
    ],
  },
  {
    id: 'p3-casse',
    season: 3,
    room: 'attic',
    title: 'On casse une dizaine',
    intro: 'Pour donner des pots, il faut ouvrir une caisse de dix.',
    competenceId: 'cassage-dizaine',
    sequence: [
      { type: 'group-ten', max: 50 },
      { type: 'hole-equality', max: 50 },
      { type: 'procedure-slate', max: 60 },
      { type: 'problem-4ph', max: 40, bank: 'p3' },
    ],
  },
  {
    id: 'p3-plus10',
    season: 3,
    room: 'living',
    title: 'Plus dix, moins dix',
    intro: 'Une caisse de plus, une caisse de moins. Le chiffre des dizaines change.',
    competenceId: 'plus-moins-10',
    sequence: [
      { type: 'hole-equality', max: 90 },
      { type: 'procedure-slate', max: 80 },
      { type: 'write-digits', min: 20, max: 90 },
      { type: 'compare', max: 90 },
    ],
  },
  {
    id: 'p3-comp-diz',
    season: 3,
    room: 'kitchen',
    title: 'Jusqu’à la prochaine dizaine',
    intro: '47… pour aller à 50, il manque combien ?',
    competenceId: 'complement-dizaine',
    sequence: [
      { type: 'procedure-slate', max: 80 },
      { type: 'procedure-slate', max: 90 },
      { type: 'hole-equality', max: 90 },
      { type: 'fluency', max: 20 },
    ],
  },
  {
    id: 'p3-fois',
    season: 3,
    room: 'kitchen',
    title: 'Trois fois trop de noisettes',
    intro: '3 boîtes, 7 noisettes dans chaque. C’est 3 fois 7.',
    competenceId: 'sens-multiplication',
    sequence: [
      { type: 'times-as-add', max: 24 },
      { type: 'times-as-add', max: 28 },
      { type: 'problem-4ph', max: 24, bank: 'p3' },
      { type: 'write-digits', max: 30 },
    ],
  },
  {
    id: 'p3-partage',
    season: 3,
    room: 'living',
    title: 'Tous pareil !',
    intro: 'Les Lemmings veulent la même part. Distribue un à un.',
    competenceId: 'partage',
    sequence: [
      { type: 'share', max: 20 },
      { type: 'share', max: 24 },
      { type: 'half-quarter', max: 20 },
      { type: 'problem-4ph', max: 20, bank: 'p3' },
    ],
  },
  {
    id: 'p3-moitie',
    season: 3,
    room: 'kitchen',
    title: 'Moitié, demi, quart',
    intro: 'Grizzy coupe le gâteau. Moitié, demi, quart.',
    competenceId: 'moitie-quart',
    sequence: [
      { type: 'half-quarter', max: 20 },
      { type: 'half-quarter', max: 20 },
      { type: 'share', max: 16 },
      { type: 'write-digits', max: 20 },
    ],
  },
  {
    id: 'p3-formes',
    season: 3,
    room: 'garden',
    title: 'Sommets et côtés',
    intro: 'Nomme la forme, compte les sommets et les côtés.',
    competenceId: 'formes-planes',
    sequence: [
      { type: 'shape', max: 10 },
      { type: 'shape', max: 10 },
      { type: 'grid-draw', max: 10 },
      { type: 'solid', max: 10 },
    ],
  },
  {
    id: 'p3-cm',
    season: 3,
    room: 'workshop',
    title: 'La règle du forestier',
    intro: 'Mesure le câble en centimètres.',
    competenceId: 'mesure-cm',
    sequence: [
      { type: 'length', max: 12 },
      { type: 'length', max: 12 },
      { type: 'mass', max: 10 },
      { type: 'compare', max: 20 },
    ],
  },
  {
    id: 'p3-monnaie',
    season: 3,
    room: 'chest',
    title: 'La caisse du ranger',
    intro: 'Compose 1, 2, 5, 10 euros.',
    competenceId: 'monnaie-sommes',
    sequence: [
      { type: 'money', max: 20 },
      { type: 'money', max: 20 },
      { type: 'money', max: 15 },
      { type: 'problem-4ph', max: 20, bank: 'p3' },
    ],
  },
  {
    id: 'p3-double-tab',
    season: 3,
    room: 'notebook',
    title: 'Qui a mangé quoi ?',
    intro: 'Tableau à double entrée : Grizzy, Lemmings, jours.',
    competenceId: 'tableau-2',
    sequence: [
      { type: 'tally-table', max: 12 },
      { type: 'bar-chart', max: 12 },
      { type: 'bar-chart', max: 12 },
      { type: 'compare', max: 20 },
    ],
  },

  {
    id: 'p4-79',
    season: 4,
    room: 'attic',
    title: 'Jusqu’à soixante-dix-neuf',
    intro: 'Soixante-dix, soixante-et-onze… les nombres français de la forêt.',
    competenceId: 'nombres-79',
    sequence: [
      { type: 'write-digits', min: 60, max: 79 },
      { type: 'write-digits', min: 70, max: 79 },
      { type: 'compare', max: 79 },
      { type: 'match-reps', max: 79 },
    ],
  },
  {
    id: 'p4-colonnes',
    season: 4,
    room: 'notebook',
    title: 'Unités sous unités',
    intro: 'Grizzy pose l’addition comme à l’école. Période 4.',
    competenceId: 'add-posee',
    sequence: [
      { type: 'column-add', max: 99 },
      { type: 'column-add', max: 99 },
      { type: 'column-add', max: 99 },
      { type: 'hole-equality', max: 40 },
    ],
  },
  {
    id: 'p4-plus9',
    season: 4,
    room: 'living',
    title: 'Le truc du plus 9',
    intro: 'Ajouter 9, c’est ajouter 10 puis retirer 1. L’ardoise de Grizzy.',
    competenceId: 'plus9',
    sequence: [
      { type: 'procedure-slate', max: 80 },
      { type: 'procedure-slate', max: 80 },
      { type: 'fluency', max: 20 },
      { type: 'write-digits', max: 90 },
    ],
  },
  {
    id: 'p4-deux',
    season: 4,
    room: 'kitchen',
    title: 'Deux nombres à additionner',
    intro: 'Dizaines avec dizaines, unités avec unités.',
    competenceId: 'add-deux',
    sequence: [
      { type: 'procedure-slate', max: 90 },
      { type: 'column-add', max: 99 },
      { type: 'problem-4ph', max: 30, bank: 'p4' },
      { type: 'hole-equality', max: 40 },
    ],
  },
  {
    id: 'p4-2etapes',
    season: 4,
    room: 'living',
    title: 'Bus des Lemmings',
    intro: 'Des Lemmings descendent, d’autres montent. Deux étapes.',
    competenceId: 'pb-2etapes',
    sequence: [
      { type: 'problem-4ph', max: 30, bank: 'p4' },
      { type: 'problem-4ph', max: 30, bank: 'p4' },
      { type: 'times-as-add', max: 24 },
      { type: 'share', max: 24 },
    ],
  },
  {
    id: 'p4-fois-pb',
    season: 4,
    room: 'kitchen',
    title: 'Paquets de biscuits',
    intro: '3 paquets de 7. Cherche le tout avec des croix ou une addition répétée.',
    competenceId: 'pb-multiplicatif',
    sequence: [
      { type: 'times-as-add', max: 28 },
      { type: 'times-as-add', max: 30 },
      { type: 'share', max: 24 },
      { type: 'problem-4ph', max: 30, bank: 'p4' },
    ],
  },
  {
    id: 'p4-heure',
    season: 4,
    room: 'clock',
    title: 'L’heure du dodo',
    intro: 'Il est huit heures. Petite aiguille sur le 8, grande sur le 12.',
    competenceId: 'heure-entiere',
    sequence: [
      { type: 'clock', max: 12 },
      { type: 'clock', max: 12 },
      { type: 'clock', max: 12 },
      { type: 'write-digits', max: 12 },
    ],
  },
  {
    id: 'p4-grille',
    season: 4,
    room: 'garden',
    title: 'Le tapis à carreaux',
    intro: 'Reproduis le motif sur le quadrillage.',
    competenceId: 'quadrillage',
    sequence: [
      { type: 'grid-draw', max: 10 },
      { type: 'grid-draw', max: 10 },
      { type: 'shape', max: 10 },
      { type: 'move-code', max: 10 },
    ],
  },
  {
    id: 'p4-ordinaux',
    season: 4,
    room: 'living',
    title: 'Le vingtième Lemming',
    intro: 'Qui est le quatrième ? Le vingtième ? File devant la télé.',
    competenceId: 'ordinaux-20',
    sequence: [
      { type: 'ordinal', max: 10 },
      { type: 'ordinal', max: 12 },
      { type: 'number-line', max: 20 },
      { type: 'write-digits', max: 20 },
    ],
  },

  {
    id: 'p5-100',
    season: 5,
    room: 'attic',
    title: 'Maître des cent pots',
    intro: 'Dernière saison : tous les nombres jusqu’à 100.',
    competenceId: 'nombres-100-fin',
    sequence: [
      { type: 'write-digits', min: 80, max: 100 },
      { type: 'compare', max: 100 },
      { type: 'match-reps', max: 99 },
      { type: 'column-add', max: 99 },
    ],
  },
  {
    id: 'p5-fluence',
    season: 5,
    room: 'living',
    title: 'Défi télé : une minute',
    intro: 'Huit égalités. Grizzy chronomètre sans stress : on s’entraîne d’abord.',
    competenceId: 'fluence-faits',
    sequence: [
      { type: 'fluency', max: 20 },
      { type: 'hole-equality', max: 20 },
      { type: 'fluency', max: 20 },
      { type: 'write-digits', max: 20 },
    ],
  },
  {
    id: 'p5-doubles',
    season: 5,
    room: 'kitchen',
    title: 'Double de quarante',
    intro: 'Doubles de 1 à 10, et doubles de 20, 30, 40, 50.',
    competenceId: 'doubles-dizaines',
    sequence: [
      { type: 'hole-equality', max: 20 },
      { type: 'times-as-add', max: 20 },
      { type: 'half-quarter', max: 20 },
      { type: 'fluency', max: 20 },
    ],
  },
  {
    id: 'p5-moities',
    season: 5,
    room: 'kitchen',
    title: 'La moitié de soixante',
    intro: 'Moitié de 40, 60, 80, 100, et des pairs jusqu’à 20.',
    competenceId: 'moities',
    sequence: [
      { type: 'half-quarter', max: 20 },
      { type: 'half-quarter', max: 20 },
      { type: 'share', max: 20 },
      { type: 'write-digits', max: 50 },
    ],
  },
  {
    id: 'p5-solides',
    season: 5,
    room: 'attic',
    title: 'Cartons du grenier',
    intro: 'Cube : 6 faces carrées. Pavé : faces carrées ou rectangles. Faces, sommets.',
    competenceId: 'solides',
    sequence: [
      { type: 'solid', max: 10 },
      { type: 'solid', max: 10 },
      { type: 'shape', max: 10 },
      { type: 'grid-draw', max: 10 },
    ],
  },
  {
    id: 'p5-barres',
    season: 5,
    room: 'notebook',
    title: '1 cube = 1 Lemming',
    intro: 'Construis et lis un diagramme en barres.',
    competenceId: 'graphique-barres',
    sequence: [
      { type: 'bar-chart', max: 12 },
      { type: 'bar-chart', max: 12 },
      { type: 'tally-table', max: 12 },
      { type: 'problem-4ph', max: 30, bank: 'p5' },
    ],
  },
]

export function missionsForSeason(season: number): Mission[] {
  return MISSIONS.filter((m) => m.season === season)
}

export function missionById(id: string): Mission | undefined {
  return MISSIONS.find((m) => m.id === id)
}

export function nextMissionId(done: string[]): string | null {
  const next = MISSIONS.find((m) => !done.includes(m.id))
  return next?.id ?? null
}
